INSERT INTO Product (ID,Name,Description,Price,AvailableQuantitiy,SupplierID)
VALUES
  (1,"velit in aliquet lobortis,","a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis","13.47",723,5),
  (2,"tellus sem mollis","Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum","72.37",975,6),
  (3,"nisi dictum augue malesuada","non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper","50.15",728,2),
  (4,"libero et","Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis","3.02",720,1),
  (5,"Nam interdum enim","sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede","3.34",589,4),
  (6,"sit amet, dapibus","lacus, varius et, euismod et, commodo at, libero.","25.86",749,8),
  (7,"tortor. Nunc commodo","Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at","56.87",196,3),
  (8,"dui, nec tempus mauris","sociis natoque penatibus et magnis","15.54",597,8),
  (9,"eu elit. Nulla facilisi.","Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo","70.82",697,6),
  (10,"sagittis.","et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus.","97.63",98,8),
  (11,"Fusce feugiat. Lorem","quam, elementum at, egestas a,","62.64",612,2),
  (12,"sapien. Cras","molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie","75.54",465,3),
  (13,"ornare.","facilisis facilisis, magna tellus faucibus leo, in lobortis","15.48",410,10),
  (14,"rutrum","arcu vel quam","40.26",306,6),
  (15,"vel turpis. Aliquam adipiscing","nunc id enim. Curabitur massa. Vestibulum accumsan neque et","91.94",208,7),
  (16,"a, auctor","varius et, euismod et, commodo at, libero. Morbi accumsan","43.40",674,10),
  (17,"faucibus orci","diam nunc, ullamcorper","67.39",383,2),
  (18,"porttitor","scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis","57.87",285,6),
  (19,"mi lorem, vehicula et,","vulputate velit eu sem. Pellentesque","9.16",753,4),
  (20,"lorem,","Donec dignissim magna a tortor. Nunc commodo","59.22",468,9),
  (21,"netus et","nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus,","65.72",651,2),
  (22,"ultrices a,","Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis","43.96",679,1),
  (23,"Nunc","dui. Fusce aliquam, enim nec tempus","12.77",438,9),
  (24,"dapibus","fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare","18.54",406,7),
  (25,"et ipsum","magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus","64.35",813,4),
  (26,"lorem, auctor","parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede","52.09",486,2),
  (27,"Duis dignissim tempor arcu.","eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed,","51.65",32,6),
  (28,"molestie dapibus ligula. Aliquam","orci. Phasellus dapibus quam quis diam. Pellentesque","51.66",823,7),
  (29,"risus. Nunc ac","montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl.","24.51",465,8),
  (30,"Pellentesque","tempor diam dictum sapien. Aenean massa. Integer vitae","68.53",801,8),
  (31,"nonummy ultricies","sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis","47.66",21,10),
  (32,"in","nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet,","19.30",739,2),
  (33,"ultricies ornare, elit","justo.","64.59",430,10),
  (34,"Fusce fermentum fermentum arcu.","ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam","95.59",614,2),
  (35,"tincidunt pede ac","non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem","70.21",587,4),
  (36,"ipsum.","Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla","80.66",834,6),
  (37,"eget mollis lectus","elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu","31.84",560,5),
  (38,"Phasellus","hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui","5.31",749,2),
  (39,"Nulla tempor","Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum","81.97",296,10),
  (40,"Nullam feugiat placerat","iaculis","46.91",930,7),
  (41,"lectus sit","dictum eleifend,","40.87",695,8),
  (42,"tempor,","commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non,","52.37",271,4),
  (43,"ac urna. Ut","viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies","50.52",853,10),
  (44,"libero nec","ipsum. Suspendisse sagittis. Nullam","2.84",669,9),
  (45,"non, dapibus rutrum,","blandit at, nisi. Cum","77.19",594,6),
  (46,"enim.","at, velit. Cras lorem","95.40",390,7),
  (47,"vitae","ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor.","18.05",537,7),
  (48,"molestie arcu. Sed","hendrerit. Donec porttitor tellus","0.61",576,5),
  (49,"In mi","pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu.","28.80",288,3),
  (50,"risus. Donec egestas.","est ac facilisis facilisis, magna tellus faucibus leo, in lobortis","79.71",18,7),
  (51,"mi, ac","ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante","14.39",981,4),
  (52,"sit amet, risus. Donec","Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus.","31.50",251,2),
  (53,"magna.","neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet,","94.76",320,10),
  (54,"Duis volutpat nunc sit","tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus","62.95",345,6),
  (55,"sed","egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui,","0.89",561,1),
  (56,"dolor. Quisque tincidunt","elit, pretium et, rutrum non,","75.18",650,9),
  (57,"consectetuer mauris id","Sed","8.99",308,9),
  (58,"diam. Duis mi enim,","Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer","19.02",126,6),
  (59,"vitae semper egestas,","Nullam feugiat","71.06",674,4),
  (60,"hendrerit a,","vulputate velit eu sem. Pellentesque ut ipsum ac mi","41.18",984,4),
  (61,"sagittis placerat.","interdum feugiat. Sed","76.41",368,9),
  (62,"Fusce fermentum fermentum","vulputate mauris sagittis placerat.","16.66",271,8),
  (63,"egestas. Aliquam fringilla","enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget","46.81",965,10),
  (64,"Nunc ac sem","Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque","79.85",90,4),
  (65,"sagittis. Duis gravida. Praesent","Quisque porttitor eros nec","2.45",534,5),
  (66,"Suspendisse","interdum libero dui nec","75.00",383,10),
  (67,"interdum feugiat.","magna. Ut tincidunt","67.84",777,6),
  (68,"at","mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate,","47.16",220,7),
  (69,"lacinia vitae, sodales at,","ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc","7.46",746,7),
  (70,"gravida sit amet,","Donec vitae erat vel pede","81.72",671,2),
  (71,"sagittis lobortis","Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci.","32.99",349,5),
  (72,"vulputate,","libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu","51.57",638,10),
  (73,"nulla magna, malesuada vel,","Mauris vestibulum, neque sed","53.90",660,1),
  (74,"velit eu sem.","sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium","32.70",672,3),
  (75,"a, enim. Suspendisse","hendrerit","97.80",833,2),
  (76,"a felis ullamcorper","pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante","91.58",512,1),
  (77,"tempor","Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum","87.14",723,8),
  (78,"hendrerit","Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim","27.61",394,7),
  (79,"molestie tellus. Aenean","mi felis, adipiscing fringilla,","90.97",598,2),
  (80,"Nullam scelerisque","id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non,","59.23",982,6),
  (81,"purus,","mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum,","20.96",766,9),
  (82,"lorem, luctus ut,","convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor,","13.96",110,9),
  (83,"quis, pede. Praesent","scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat","69.04",419,7),
  (84,"id, blandit at,","ac","89.32",386,10),
  (85,"Duis elementum, dui","nascetur ridiculus mus. Aenean eget","29.59",82,9),
  (86,"nec, cursus","non, bibendum sed, est. Nunc laoreet lectus quis","13.34",840,9),
  (87,"Vivamus nisi.","et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu,","9.74",781,6),
  (88,"magna. Lorem ipsum","est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor","6.58",256,4),
  (89,"molestie sodales. Mauris blandit","Morbi sit amet massa. Quisque porttitor eros","13.77",378,2),
  (90,"malesuada","et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus.","12.35",426,9),
  (91,"tempus mauris","quam vel","9.07",222,4),
  (92,"urna.","eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam","52.47",694,9),
  (93,"lorem ipsum sodales","ac tellus.","99.93",381,1),
  (94,"sit","pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor","51.03",560,6),
  (95,"neque. Morbi quis urna.","eget metus. In nec orci. Donec","57.85",95,8),
  (96,"Mauris vel","mi, ac mattis velit justo nec ante. Maecenas mi","16.03",178,10),
  (97,"Nunc sed orci","nibh vulputate mauris sagittis placerat. Cras dictum ultricies","42.13",394,10),
  (98,"non leo.","feugiat tellus","30.62",462,2),
  (99,"aliquet libero.","bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in","2.76",137,2),
  (100,"sagittis semper. Nam tempor","lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque","95.06",361,10);
