USE ecommerce;

DROP TABLE IF EXISTS CartItem;
DROP TABLE IF EXISTS OrderItem;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Supplier;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS UserPhone;
DROP TABLE IF EXISTS User;
